title = getTitle();
run("Set Measurements...", "area mean min shape redirect=None decimal=3");
run("Subtract Background...", "rolling=20 light");
setAutoThreshold("Triangle");
//run("Threshold...");
setThreshold(0, 50835);
setOption("BlackBackground", true);
run("Convert to Mask");
run("Analyze Particles...", "size=2000-Infinity pixel show=Outlines clear add");
selectWindow("Drawing of " + title);
roiManager("Measure");
